### ISSUE TITLE
BasiliskII: running an autotools build breaks ability to build with Xcode 

### ISSUE THREAD

**Issue by rickyzhang82** [DavidLudwig/macemu#15] opened 2017-08-13 21:01 UTC
I use commit c6fefd0750f7c5df34013464e6c87cf98d93b77f.

Get SDL v2 submodule
```bash
git submodule update --recursive --remote --init
```

Open project file macemu/BasiliskII/src/MacOSX/BasiliskII.xcodeproj. I have the following compile error:

```log
CompileC /Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Intermediates/BasiliskII.build/Debug/BasiliskII.build/Objects-normal/x86_64/fpu_uae.o /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/Ricky/repo/github/macemu/BasiliskII/src/MacOSX
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu++11 -stdlib=libc++ -fmodules -gmodules -fmodules-cache-path=/Users/Ricky/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/Ricky/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Werror=deprecated-objc-isa-usage -Werror=objc-root-class -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -mmacosx-version-min=10.7 -g -fvisibility-inlines-hidden -Wno-sign-conversion -Winfinite-recursion -Wmove -iquote /Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Intermediates/BasiliskII.build/Debug/BasiliskII.build/BasiliskII-generated-files.hmap -I/Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Intermediates/BasiliskII.build/Debug/BasiliskII.build/BasiliskII-own-target-headers.hmap -I/Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Intermediates/BasiliskII.build/Debug/BasiliskII.build/BasiliskII-all-target-headers.hmap -iquote /Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Intermediates/BasiliskII.build/Debug/BasiliskII.build/BasiliskII-project-headers.hmap -I/Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Products/Debug/include -I/Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Products/Debug/SDL2.framework/Headers -I../UNIX -I../include -I. -I../uae_cpu -I/Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Intermediates/BasiliskII.build/Debug/BasiliskII.build/DerivedSources/x86_64 -I/Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Intermediates/BasiliskII.build/Debug/BasiliskII.build/DerivedSources -F/Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Products/Debug -F/Library/Frameworks -MMD -MT dependencies -MF /Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Intermediates/BasiliskII.build/Debug/BasiliskII.build/Objects-normal/x86_64/fpu_uae.d --serialize-diagnostics /Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Intermediates/BasiliskII.build/Debug/BasiliskII.build/Objects-normal/x86_64/fpu_uae.dia -c /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp -o /Users/Ricky/Library/Developer/Xcode/DerivedData/BasiliskII-harxfjzzbxzhpogfqyaqibwdnbzm/Build/Intermediates/BasiliskII.build/Debug/BasiliskII.build/Objects-normal/x86_64/fpu_uae.o

In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:94:
/Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/newcpu.h:216:20: warning: implicit conversion loses integer precision: 'long' to 'uaecptr' (aka 'unsigned int') [-Wshorten-64-to-32]
    return regs.pc + ((char *)regs.pc_p - (char *)regs.pc_oldp);
    ~~~~~~ ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:97:
In file included from ../uae_cpu/fpu/fpu.h:47:
../uae_cpu/fpu/core.h:59:2: error: unknown type name 'fpu_register'
        fpu_register    registers[8];
        ^
../uae_cpu/fpu/core.h:62:2: error: unknown type name 'fpu_register'
        fpu_register    result;
        ^
../uae_cpu/fpu/core.h:222:8: error: unknown type name 'fpu_register'
inline fpu_register * const fpu_register_address(int i)
       ^
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:98:
../uae_cpu/fpu/fpu_uae.h:58:16: error: unknown type name 'fpu_register'
PRIVATE inline fpu_register round_to_zero(fpu_register const & x);
               ^
../uae_cpu/fpu/fpu_uae.h:58:43: error: use of undeclared identifier 'fpu_register'; did you mean 'fpu_reset'?
PRIVATE inline fpu_register round_to_zero(fpu_register const & x);
                                          ^~~~~~~~~~~~
                                          fpu_reset
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:97:
In file included from ../uae_cpu/fpu/fpu.h:47:
../uae_cpu/fpu/core.h:244:13: note: 'fpu_reset' declared here
extern void fpu_reset(void);
            ^
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:98:
../uae_cpu/fpu/fpu_uae.h:58:9: warning: inline variables are a C++1z extension [-Wc++1z-extensions]
PRIVATE inline fpu_register round_to_zero(fpu_register const & x);
        ^
../uae_cpu/fpu/fpu_uae.h:58:56: error: expected ')'
PRIVATE inline fpu_register round_to_zero(fpu_register const & x);
                                                       ^
../uae_cpu/fpu/fpu_uae.h:58:42: note: to match this '('
PRIVATE inline fpu_register round_to_zero(fpu_register const & x);
                                         ^
../uae_cpu/fpu/fpu_uae.h:59:16: error: unknown type name 'fpu_register'
PRIVATE inline fpu_register round_to_nearest(fpu_register const & x);
               ^
../uae_cpu/fpu/fpu_uae.h:59:46: error: use of undeclared identifier 'fpu_register'; did you mean 'fpu_reset'?
PRIVATE inline fpu_register round_to_nearest(fpu_register const & x);
                                             ^~~~~~~~~~~~
                                             fpu_reset
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:97:
In file included from ../uae_cpu/fpu/fpu.h:47:
../uae_cpu/fpu/core.h:244:13: note: 'fpu_reset' declared here
extern void fpu_reset(void);
            ^
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:98:
../uae_cpu/fpu/fpu_uae.h:59:9: warning: inline variables are a C++1z extension [-Wc++1z-extensions]
PRIVATE inline fpu_register round_to_nearest(fpu_register const & x);
        ^
../uae_cpu/fpu/fpu_uae.h:59:59: error: expected ')'
PRIVATE inline fpu_register round_to_nearest(fpu_register const & x);
                                                          ^
../uae_cpu/fpu/fpu_uae.h:59:45: note: to match this '('
PRIVATE inline fpu_register round_to_nearest(fpu_register const & x);
                                            ^
../uae_cpu/fpu/fpu_uae.h:73:41: error: use of undeclared identifier 'fpu_register'; did you mean 'fpu_reset'?
PRIVATE inline void FFPU get_dest_flags(fpu_register const & r);
                                        ^~~~~~~~~~~~
                                        fpu_reset
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:97:
In file included from ../uae_cpu/fpu/fpu.h:47:
../uae_cpu/fpu/core.h:244:13: note: 'fpu_reset' declared here
extern void fpu_reset(void);
            ^
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:98:
../uae_cpu/fpu/fpu_uae.h:73:9: warning: inline variables are a C++1z extension [-Wc++1z-extensions]
PRIVATE inline void FFPU get_dest_flags(fpu_register const & r);
        ^
../uae_cpu/fpu/fpu_uae.h:73:26: error: variable has incomplete type 'void'
PRIVATE inline void FFPU get_dest_flags(fpu_register const & r);
                         ^
../uae_cpu/fpu/fpu_uae.h:73:54: error: expected ')'
PRIVATE inline void FFPU get_dest_flags(fpu_register const & r);
                                                     ^
../uae_cpu/fpu/fpu_uae.h:73:40: note: to match this '('
PRIVATE inline void FFPU get_dest_flags(fpu_register const & r);
                                       ^
../uae_cpu/fpu/fpu_uae.h:74:43: error: use of undeclared identifier 'fpu_register'; did you mean 'fpu_reset'?
PRIVATE inline void FFPU get_source_flags(fpu_register const & r);
                                          ^~~~~~~~~~~~
                                          fpu_reset
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:97:
In file included from ../uae_cpu/fpu/fpu.h:47:
../uae_cpu/fpu/core.h:244:13: note: 'fpu_reset' declared here
extern void fpu_reset(void);
            ^
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:98:
../uae_cpu/fpu/fpu_uae.h:74:9: warning: inline variables are a C++1z extension [-Wc++1z-extensions]
PRIVATE inline void FFPU get_source_flags(fpu_register const & r);
        ^
../uae_cpu/fpu/fpu_uae.h:74:26: error: variable has incomplete type 'void'
PRIVATE inline void FFPU get_source_flags(fpu_register const & r);
                         ^
../uae_cpu/fpu/fpu_uae.h:74:56: error: expected ')'
PRIVATE inline void FFPU get_source_flags(fpu_register const & r);
                                                       ^
../uae_cpu/fpu/fpu_uae.h:74:42: note: to match this '('
PRIVATE inline void FFPU get_source_flags(fpu_register const & r);
                                         ^
../uae_cpu/fpu/fpu_uae.h:76:35: error: use of undeclared identifier 'fpu_register'; did you mean 'fpu_reset'?
PRIVATE inline bool FFPU do_isnan(fpu_register const & r);
                                  ^~~~~~~~~~~~
                                  fpu_reset
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:97:
In file included from ../uae_cpu/fpu/fpu.h:47:
../uae_cpu/fpu/core.h:244:13: note: 'fpu_reset' declared here
extern void fpu_reset(void);
            ^
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:98:
../uae_cpu/fpu/fpu_uae.h:76:9: warning: inline variables are a C++1z extension [-Wc++1z-extensions]
PRIVATE inline bool FFPU do_isnan(fpu_register const & r);
        ^
../uae_cpu/fpu/fpu_uae.h:76:48: error: expected ')'
PRIVATE inline bool FFPU do_isnan(fpu_register const & r);
                                               ^
../uae_cpu/fpu/fpu_uae.h:76:34: note: to match this '('
PRIVATE inline bool FFPU do_isnan(fpu_register const & r);
                                 ^
../uae_cpu/fpu/fpu_uae.h:76:35: warning: address of function 'fpu_reset' will always evaluate to 'true' [-Wpointer-bool-conversion]
PRIVATE inline bool FFPU do_isnan(fpu_register const & r);
                         ~~~~~~~~ ^~~~~~~~~~~~
../uae_cpu/fpu/fpu_uae.h:76:35: note: prefix with the address-of operator to silence this warning
PRIVATE inline bool FFPU do_isnan(fpu_register const & r);
                                  ^
                                  &
../uae_cpu/fpu/fpu_uae.h:77:35: error: use of undeclared identifier 'fpu_register'; did you mean 'fpu_reset'?
PRIVATE inline bool FFPU do_isinf(fpu_register const & r);
                                  ^~~~~~~~~~~~
                                  fpu_reset
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:97:
In file included from ../uae_cpu/fpu/fpu.h:47:
../uae_cpu/fpu/core.h:244:13: note: 'fpu_reset' declared here
extern void fpu_reset(void);
            ^
In file included from /Users/Ricky/repo/github/macemu/BasiliskII/src/uae_cpu/fpu/fpu_uae.cpp:98:
../uae_cpu/fpu/fpu_uae.h:77:9: warning: inline variables are a C++1z extension [-Wc++1z-extensions]
PRIVATE inline bool FFPU do_isinf(fpu_register const & r);
        ^
../uae_cpu/fpu/fpu_uae.h:77:48: error: expected ')'
PRIVATE inline bool FFPU do_isinf(fpu_register const & r);
                                               ^
../uae_cpu/fpu/fpu_uae.h:77:34: note: to match this '('
PRIVATE inline bool FFPU do_isinf(fpu_register const & r);
                                 ^
../uae_cpu/fpu/fpu_uae.h:77:35: warning: address of function 'fpu_reset' will always evaluate to 'true' [-Wpointer-bool-conversion]
PRIVATE inline bool FFPU do_isinf(fpu_register const & r);
                         ~~~~~~~~ ^~~~~~~~~~~~
../uae_cpu/fpu/fpu_uae.h:77:35: note: prefix with the address-of operator to silence this warning
PRIVATE inline bool FFPU do_isinf(fpu_register const & r);
                                  ^
                                  &
fatal error: too many errors emitted, stopping now [-ferror-limit=]
9 warnings and 20 errors generated.
```

**Comment by DavidLudwig** [comment] 2017-08-13 23:58
Can you post a copy of the entire build log (as opposed to just the error-laden snippet near its end)?

**Comment by rickyzhang82** [comment] 2017-08-14 01:09
[Log](https://docs.google.com/document/d/1KDUqCzT5FeYd_IyfPQIHtyIT4bPqLdZaMwYmF2H9kVM/edit?usp=sharing)

**Comment by DavidLudwig** [comment] 2017-08-14 14:04
I'm having trouble reproducing this, unfortunately.

Did you apply any modifications to the Basilisk source code, or to Xcode?

What command(s) did you use to retrieve the macemu repository?

**Comment by rickyzhang82** [comment] 2017-08-14 20:07
No. I did no modification.

I added your repo as another remote repo in the same location of mine locally. But I did 'make clean' with GNU automake in UNIX folder before run XCode build.

Maybe I should try it again in another local location from scratch. If I still have issues, I'd get you back. You may try it by yourself from scratch in another location.

**Comment by rickyzhang82** [comment] 2017-08-15 00:46
I clone it to a new location. It resolve the problem. It seems that GNU automake has left over files that break XCode build.

**Comment by rickyzhang82** [comment] 2017-08-15 00:58
@DavidLudwig I will leave this open. I will come back and see what generated files from GNU automake break the XCode build.

**Comment by DavidLudwig** [comment] 2017-08-19 23:00
I suspect that the autotools build is overwriting some of the 68k emulator files.

**Comment by DavidLudwig** [comment] 2017-08-19 23:00
Thanks for the info on this!

**Comment by DavidLudwig** [comment] 2017-08-27 21:06
This may be fixed via a checkin that I just pushed to Github, https://github.com/DavidLudwig/macemu/commit/51a9eeae7605e78ed9d884b0953d993d0e0f98e7

I have yet to test that fix, as a fix for this case.

**Comment by DavidLudwig** [comment] 2017-08-27 21:13
That fix (https://github.com/DavidLudwig/macemu/commit/51a9eeae7605e78ed9d884b0953d993d0e0f98e7) does -not- fix this case.  I am able to reproduce it both with it, and without it.

**Comment by DavidLudwig** [comment] 2017-08-27 21:34
It looks like what is happening is when the autoconf/configure script is run, a config.h will be generated in BasiliskII/src/Unix.  If and when other header files in that directory are generated, such as sysdeps.h, it'll lead to the MacOSX specific copy of config.h (in BasiliskII/src/MacOSX), in some cases, not being used.

Changing the order of includes in the BasiliskII Xcode project does not fix this.

**Comment by DavidLudwig** [comment] 2017-08-27 22:06
Fixed via https://github.com/DavidLudwig/macemu/commit/145ca0c210559dc67ce266f7e6df8b6391327887

**Closed by DavidLudwig** 2017-08-27 22:06 UTC
